### ISSUE TITLE
Answer to flow case.js question

### ISSUE THREAD

**Issue by marudor** [DJCordhose/flow-vs-typescript#1]
You've got the following ```javascript
let a: 'a1' | 'a2' = 'a1';
switch (a) {
    case 'a1': console.log('a1'); break;
    case 'a2': console.log('a2'); break;
    case 'a3': console.log('why is this legal code???'); break;
    default: console.log('and why this?');
}```

The last 2 cases "work" because flow just does not give you an  error for switches but is more permissive than usual.
Flow correctly notices that in case a1 a is a string - same for a2. In a3 and default it is just any as there are no more cases left that would be possible.
Following example:
```javascript
function foo(): string {
  let b: 'a1' | 'a2' | 1 = 'a1';
  switch (b) {
    case 'a1': return b; // b is type 'a2' | 1 
    case 'a2': return b; // b is type 1
    case 1: return 'foo'; // b is type any
    case 2: return 'foo'; // b is never 2 - flow doesnt know though as it fell back to type any
    default: return b; // works due to type any
  }
}```

As you can see - flow noticed that there is no valid type left for b and fell back to any. This is as flow does not have a type for "nothing" (A type that matches no type.)

**Comment by DJCordhose** [comment]
Thanks for your help. As discussed here

https://github.com/facebook/flow/issues/1473

Flow should probably catch that one as OCaml does so as well.
