### ISSUE TITLE
Non-nullable types are now present in TypeScript

### ISSUE THREAD

**Issue by GabrielDelepine** [DJCordhose/flow-vs-typescript#6]
Hi,

Thanks for your nice job !

Typescript 2.0 introduce the non-nullable types.
This slide has to be updated : http://djcordhose.github.io/flow-vs-typescript/2016_hhjs.html#/15

Thanks !

**Comment by DJCordhose** [comment]
Hi, Gabriel,

thanks a lot 👍 

That talk is just a snap shot of a slide deck that is work in progress. I have linked to it on slide one:

http://djcordhose.github.io/flow-vs-typescript/2016_hhjs.html#/

and this is the direct link that gets updated frequently

http://djcordhose.github.io/flow-vs-typescript/flow-typescript-2.html
